-- MySQL Script generated by MySQL Workbench
-- Sat Oct 14 13:26:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `IDUsuario` INT NOT NULL,
  `Nome` VARCHAR(25) NULL,
  `Sobrenome` VARCHAR(25) NULL,
  `CPF` VARCHAR(14) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`IDUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locais` (
  `IDLocais` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`IDLocais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lancamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lancamento` (
  `IDLancamento` INT NOT NULL,
  `Data` DATETIME NULL,
  `Horario` VARCHAR(8) NULL,
  `IDUsuario` INT NOT NULL,
  `IDLocais` INT NOT NULL,
  PRIMARY KEY (`IDLancamento`, `IDUsuario`, `IDLocais`),
  INDEX `fk_Lancamento_Usuario1_idx` (`IDUsuario` ASC) VISIBLE,
  INDEX `fk_Lancamento_Locais1_idx` (`IDLocais` ASC) VISIBLE,
  CONSTRAINT `fk_Lancamento_Usuario1`
    FOREIGN KEY (`IDUsuario`)
    REFERENCES `mydb`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lancamento_Locais1`
    FOREIGN KEY (`IDLocais`)
    REFERENCES `mydb`.`Locais` (`IDLocais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DoadoresLocais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DoadoresLocais` (
  `IDDoadoresLocais` INT NOT NULL,
  `TipoSangue` VARCHAR(3) NULL,
  `IDUsuario` INT NOT NULL,
  `IDLocais` INT NOT NULL,
  PRIMARY KEY (`IDDoadoresLocais`, `IDUsuario`, `IDLocais`),
  INDEX `fk_DoadoresLocais_Usuario_idx` (`IDUsuario` ASC) VISIBLE,
  INDEX `fk_DoadoresLocais_Locais1_idx` (`IDLocais` ASC) VISIBLE,
  CONSTRAINT `fk_DoadoresLocais_Usuario`
    FOREIGN KEY (`IDUsuario`)
    REFERENCES `mydb`.`Usuario` (`IDUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DoadoresLocais_Locais1`
    FOREIGN KEY (`IDLocais`)
    REFERENCES `mydb`.`Locais` (`IDLocais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
